CoreApp/MicroService_QLBanDienThoai/Areas/Admin/Controllers/WareHousingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using MicroService_QLBanDienThoai.Areas.Admin.Models;
using MicroService_QLBanDienThoai.Areas.Customer.Models;
using MicroService_QLBanDienThoai.BUS;
using MicroService_QLBanDienThoai.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.BUS;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MicroService_QLBanDienThoai.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WareHousingController : BaseController
    {
        public IActionResult Index()
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8082");
                MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
                client.DefaultRequestHeaders.Accept.Add(contentType);
                HttpResponseMessage response = client.GetAsync("/api/receipt_note").Result;
                string strData = response.Content.ReadAsStringAsync().Result;
                List<ViewReceipt> result = JsonConvert.DeserializeObject<List<ViewReceipt>>(strData);
                if (result.Count == 0)
                    return View();
                return View(result);
            }
        }
        public IActionResult Create()
        {
            ProductBUS _product = new ProductBUS();
            ViewBag.Product = _product.GetProduct();
            return View();
        }
        public IActionResult Detail(string id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8082");
                MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
                client.DefaultRequestHeaders.Accept.Add(contentType);
                HttpResponseMessage response = client.GetAsync("/api/detail_receipt/").Result;
                string strData = response.Content.ReadAsStringAsync().Result;
                List<Detail_Adapter> temp = JsonConvert.DeserializeObject<List<Detail_Adapter>>(strData);
                if (temp.Count == 0)
                    return View();
                decimal amount = 0;
                ProductBUS productBUS = new ProductBUS();
                List<Detail_Adapter> result = new List<Detail_Adapter>();
                foreach (var item in temp)
                {
                    if (item.Receipt_ID == (int.Parse(id)))
                    {
                        amount += productBUS.GetSanPham(item.Product_ID.ToString()).Price * item.Quantity;
                        result.Add(item);
                    }
                }
                ViewBag.Amount = amount;
                return View(result);
            }
        }
        public IActionResult GetProduct(string id)
        {
            
            ProductBUS _bus = new ProductBUS();
            Product temp = _bus.GetSanPham(id);

            var result = new {
                Id=new Guid(),
                ProductId=temp.ProductId,
                Name=temp.Name,
                Image=temp.Image,
                Quantity=temp.Quantity,
                Price=temp.Price,
            };
            return Json(result);
        }
        public IActionResult CreateReceipt(string[] product, string[] quantity, string amount)
        {
            string check = HttpContext.Session.GetString("TenDangNhap");
            if (String.IsNullOrEmpty(check))
            {
                return Redirect("/");
            }
            ProductBUS _product_bus = new ProductBUS();
            List<ViewDetail_receipt> _list = new List<ViewDetail_receipt>();
            for (int i = 0; i < product.Length; i++)
            {
                ViewDetail_receipt toInsert = new ViewDetail_receipt();
                toInsert.Product_ID = int.Parse(product[i]);
                toInsert.Quantity = int.Parse(quantity[i]);
                _list.Add(toInsert);
                Product toUpdate = _product_bus.GetSanPham(product[i]);
                toUpdate.Quantity += int.Parse(quantity[i]);
                _product_bus.UpdateProduct(toUpdate);
            }

            float _amount = float.Parse(amount);
            AccountBUS _bus = new AccountBUS();
            Account _account = _bus.GetAccountByName(check);
            var obj = new
            {
                AccountID = _account.AccountId,
                Amount = _amount,
                State_Receipt = 1,
                Success_At = DateTime.Now,
                Is_Active = "True",
                Archive = "True",
                Detail_Receipts = _list,
            };
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8082");
                MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
                client.DefaultRequestHeaders.Accept.Add(contentType);
                string stringData = JsonConvert.SerializeObject(obj);
                var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                System.Diagnostics.Debug.WriteLine(contentData);
                HttpResponseMessage response = client.PostAsync("/api/receipt_note/", contentData).Result;
                string result = response.Content.ReadAsStringAsync().Result;
                if (result == "\"Thanh cong\"")
                {
                    return Json("Thanh toán thành công");
                }
                else
                {
                    for (int i = 0; i < product.Length; i++)
                    {
                        Product toUpdate = _product_bus.GetSanPham(product[i]);
                        toUpdate.Quantity -= int.Parse(quantity[i]);
                        _product_bus.UpdateProduct(toUpdate);
                    }
                    return Json(result);
                }
            }
        }
    }
}

CoreApp/MicroService_QLBanDienThoai/Areas/Admin/Views/WareHousing/Create.cshtml

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;
@{
    List<MicroService_QLBanDienThoai.Models.Product> _list = (List<MicroService_QLBanDienThoai.Models.Product>)ViewBag.Product;
}

<h1 class="page-header">THÊM MỚI NHẬP KHO</h1>
<hr>

<div class="panel panel-default">
    <div class="panel-body">
        <!-- Search form -->

        <br />
        <div class="col-lg-8">

            <div class="col-lg-6" style="display:inline-block;float:left;">
                <p>Nguời Nhập:</p> <input type="text" class="form-control" readonly="readonly" value="@Context.Session.GetString("TenDangNhap")" id="searchList" name="search">
            </div>
            <div class="col-lg-6" style="display:inline-block;float:left;">
                <p>Tổng Tiền: </p><input type="text" class="form-control" readonly="readonly" value="0" id="sum_amount" placeholder="" name="">
            </div>
            <div class="col-lg-5" style="display:inline-block;float:left;">
                <p>Ngày Nhập</p> <input type="text" readonly="readonly" class="form-control" value="@DateTime.Now" id="" placeholder="" name="">
            </div>
            <div class="col-lg-5" style="display:inline-block;float:left;">
                <p>Mã Sản Phẩm:</p>
                <select class="form-control" id="select_product">
                    @{
                        foreach (var item in _list)
                        {
                            <option value="@item.ProductId">@item.ProductId</option>
                        }
                    }
                </select>
            </div>
            <div class="col-lg-2" style="display:inline-block;float:left;">
                <p>Chuc nang</p>
                <a href="" id="add_product" class="form-control btn btn-info">Them</a>
            </div>
        </div>
        <script>
            function insert_product(quantity, price) {
                var sum_amount = parseFloat($('#sum_amount').val())
                var _quantity = parseInt(quantity);
                var _price = parseInt(price);
                sum_amount += _quantity * _price;
                $('#sum_amount').attr('value', sum_amount)
            }
            function removeproduct(a) {
                var elem = document.getElementById('result_insert');
                elem.parentNode.removeChild(a);
            }
            $('#add_product').click(function (e) {
                e.preventDefault();
                var SP = $('#select_product').val();
                var data = {
                    id: SP,
                };
                $.ajax({
                    url: "/Admin/WareHousing/GetProduct",
                    type: "post",
                    data: data,
                    success: function (data) {
                        var html = '';
                        html += '<tr style="vertical-align: middle;" class="odd gradeX" id="' + data['id'] + '">'
                        html += ' <td style="vertical-align: middle;" class="item-AccountID list_product">' + data['productId'] + ' </td>'
                        html += '<td style="vertical-align: middle;" class="item-AccountName">' + data['name'] + '</td>'
                        html += '<td style="vertical-align: middle;" class="item-AccountName"> <img style="max-width:15%" src="/HinhSanPham/' + data['image'] + '"/></td>'
                        html += '<td style="vertical-align: middle;" class="item-AccountName"><input id="quan' + data['productId'] + '" onchange="insert_product(this.value,' + data['price'] + ')" value="0"></td>'
                        html += '<td style="vertical-align: middle;"><a asp-controller="" asp-action=""onclick="removeproduct("' + data['id'] + '");return false;"  asp-route-accountid="" class="btn btn-danger">Xóa</a></td>'
                        $('#result_insert').append(html);
                    },
                    error: function (data) {
                        alert("Error: " + data);
                    }
                })
            })
           
           

        </script>
        <div class="clearfix"></div>
        <br />
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead class="thead-dark">
                <tr>
                    <th>Mã sản phẩm</th>
                    <th>Tên sản phẩm</th>
                    <th>Hình ảnh</th>
                    <th>Số lượng</th>
                    <th>Chức Năng</th>
                </tr>
            </thead>
            <tbody class="body-content" id="result_insert"></tbody>
        </table>
        <a id="confirm_receipt" class="form-control btn btn-info">Nhap kho</a>
    </div>
</div>
<script>
    $('#confirm_receipt').click(function (e) {
        e.preventDefault();
        var product = [];
        var quantity = [];
        $(".list_product").each(function () {
            if ($('#quan' + $(this).html()).val() < 1) {
                alert('So luong khong phu hop');
                return false;
            }
            product.push($(this).html())
            quantity.push($('#quan' + $(this).html()).val());
        });
        var input_data = {
            product: product,
            quantity: quantity,
            amount: $('#sum_amount').val(),
        }
        $.ajax({
            url: "/Admin/WareHousing/CreateReceipt",
            type: "post",
            data: input_data,
            success: function (data) {
                alert("Nhập kho thành công");
            },
            error: function (data) {
                alert("Error: "+data);
            }
        })
    })
</script>
<!-- /.table-responsive -->
<!-- /.panel-body -->

@if (ViewBag.ThongBao != null)
{
    <script>
        alert("@Html.Raw(ViewBag.ThongBao)");
    </script>
}



CoreApp/MicroService_QLBanDienThoai/Areas/Admin/Views/WareHousing/Detail.cshtml

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;
@model List<MicroService_QLBanDienThoai.Areas.Admin.Models.Detail_Adapter>


<h1 class="page-header">CHI TIẾT NHẬP KHO</h1>
<hr>

<div class="panel panel-default">
    <div class="panel-body">
        <!-- Search form -->

        <br />
        <div class="col-lg-12">

            <div class="col-lg-4" style="display:inline-block;float:left;">
                <p>Nguời Nhập:</p> <input type="text" class="form-control" readonly="readonly" value="@Context.Session.GetString("TenDangNhap")" id="searchList" name="search">
            </div>
            <div class="col-lg-4" style="display:inline-block;float:left;">
                <p>Tổng Tiền: </p><input type="text" class="form-control" readonly="readonly" value="@ViewBag.Amount.ToString("#.# VND")" id="sum_amount" placeholder="" name="">
            </div>
            <div class="col-lg-4" style="display:inline-block;float:left;">
                <p>Ngày Nhập</p> <input type="text" readonly="readonly" class="form-control" value="@DateTime.Now" id="" placeholder="" name="">
            </div>
        </div>
        <div class="clearfix"></div>
        <br />
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead class="thead-dark">
                <tr>
                    <th>Mã sản phẩm</th>
                    <th>Tên sản phẩm</th>
                    <th>Hình ảnh</th>
                    <th>Số lượng</th>

                </tr>
            </thead>
            <tbody class="body-content" id="result_insert"></tbody>
        </table>
    </div>
</div>
@{
    foreach(var item in Model)
    {
    <script>
    $(document).ready(function () {
            var data = {
                id: @item.Product_ID,
            };
            $.ajax({
                url: "/Admin/WareHousing/GetProduct",
                type: "post",
                data: data,
                success: function (data) {
                    var html = '';
                    html += '<tr style="vertical-align: middle;" class="odd gradeX" id="' + data['id'] + '">'
                    html += ' <td style="vertical-align: middle;" class="item-AccountID list_product">' + data['productId'] + ' </td>'
                    html += '<td style="vertical-align: middle;" class="item-AccountName">' + data['name'] + '</td>'
                    html += '<td style="vertical-align: middle;" class="item-AccountName"> <img style="max-width:15%" src="/HinhSanPham/' + data['image'] + '"/></td>'
                    html += '<td style="vertical-align: middle;" class="item-AccountName">' + @item.Quantity+'</td>'
                    $('#result_insert').append(html);
                },
                error: function (data) {
                    alert("Error: " + data);
                }
            })
    })
    </script>
    }

}
<!-- /.table-responsive -->
<!-- /.panel-body -->

@if (ViewBag.ThongBao != null)
{
<script>
        alert("@Html.Raw(ViewBag.ThongBao)");
</script>
}



CoreApp/MicroService_QLBanDienThoai/Areas/Admin/Views/WareHousing/Index.cshtml

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model List<MicroService_QLBanDienThoai.Areas.Admin.Models.ViewReceipt>

<h1 class="page-header">DANH SÁCH NHẬP KHO</h1>
<hr>

<div class="panel panel-default">
    <div class="panel-body">
        <!-- Search form -->
        <div class="row">
            <!-------------------------------------------------------- INSERT ---------------------------------------------------------->
            <div class="col-lg-1">
                <a asp-controller="WareHousing" asp-action="Create" method="get">
                    <button class="btn btn-primary" data-toggle="modal" data-target="#">Thêm</button>
                    </a>
            </div>
            <!-------------------------------------------------------- SEARCH CATEGORY ---------------------------------------------------------->
            @*<div class="col-lg-2">
            <div class="form-group">
                <select class="form-control" id="sortList" onchange="window.location.href = SearchAndSort()">
                    <option selected disabled>Sắp xếp theo</option>
                    <option value="/Webmaster/LoaiNguoiDung/Sort?sortorder=maloainguoidung-az">Mã loại người dùng (A-Z)</option>
                    <option value="/Webmaster/LoaiNguoiDung/Sort?sortorder=maloainguoidung-za">Mã loại người dùng (Z-A)</option>
                    <option value="/Webmaster/LoaiNguoiDung/Sort?sortorder=tenloainguoidung-az">Tên loại người dùng (A-Z)</option>
                    <option value="/Webmaster/LoaiNguoiDung/Sort?sortorder=tenloainguoidung-za">Tên loại người dùng (Z-A)</option>
                </select>
            </div>
        </div>*@
            <!-------------------------------------------------------- SEARCH BAR ---------------------------------------------------------->
            <div class="col-lg-3">
                <form asp-controller="Account" asp-action="Search" method="get">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" id="searchList" placeholder="Tìm kiếm..." name="search">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </div>

            <!-------------------------------------------------------- MAIN TABLE ---------------------------------------------------------->
        </div>
        <br />
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead class="thead-dark">
                <tr>
                    <th>Mã phiếu nhập</th>
                    <th>Mã người nhập</th>
                    <th>Tổng tiền</th>
                    <th>Ngày nhập</th>
                    <th>Chức Năng</th>
                </tr>
            </thead>
            <tbody class="body-content">
                @{
                    if (Model != null && Model.Count > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr class="odd gradeX">
                                <td width="10%" class="item-AccountID">@item.Receipt_ID </td>
                                <td width="10%" class="item-AccountName">@item.AccountID</td>
                                <td width="30%" class="item-Password">@item.Amount.ToString("#.#") đ</td>
                                <td width="30%" class="item-PhoneNumber">@item.Success_At</td>
                                <td>
                                    <a href="/Admin/WareHousing/Detail/@item.Receipt_ID" class="btn btn-danger">Chi Tiết</a>
                                </td>
                            </tr>
                        }
                    }
                }

            </tbody>
        </table>
        <!-- /.table-responsive -->
        <!-- /.panel-body -->

        @if (ViewBag.ThongBao != null)
        {
            <script>
        alert("@Html.Raw(ViewBag.ThongBao)");
            </script>
        }

